// react/src/Admin/Footer.jsx
import React from 'react'

function Footer(props) {
  return (
    <footer>
      <span className="footer-inner-wrapper">
        <p>Learn more about Skava Commerce and upcoming events at Skava.com</p>
        <h4>Privacy Policy</h4>
        <p>© 2019 Skava. All rights reserved.</p>
      </span>
    </footer>
  )
}

export { Footer }
export default Footer

// vuejs/src/components/Footer.vue
<template>
  <footer>
    <span class="footer-inner-wrapper">
      <p>Learn more about Skava Commerce and upcoming events at Skava.com</p>
      <h4>Privacy Policy</h4>
      <p>© 2019 Skava. All rights reserved.</p>
    </span>
  </footer>
</template>

<script>
export default {
  name: "Footer",
  props: {}
};
</script>

<style scoped>
</style>
