// vuejs/src/components/Container.vue
<template>
  <container class="main-container">
    <img
      src="https://admin.skavacommerce.com/admin/studio/customlib/img/loginBanner.jpg"
      alt=" Business related photo"
      class="business-picture"
    >
    <div class="form-wrapper">
      <h1 class="form-title">Sign In</h1>
      <form class="form-signin">
        <div icontype="mail" class="form-fields">
          <label class="form-label" for="maillabel">Your Email</label>
          <input type="text" id="maillabel" name="maillabel">
        </div>
        <div icontype="lock" class="form-fields">
          <label class="form-label" for="passowrdlabel">Your Password</label>
          <input type="password" id="passowrdlabel" name="passowrdlabel">
        </div>
        <div class="button-group">
          <div class="loggedin-wrapper">
            <div class="form-checkbox">
              <input checked type="checkbox" id="loggedin-checked">
              <label class="checkbox-support" for="loggedin-checked"></label>
            </div>
            <label class="loggedin-label" for="loggedin-checked">Keep me logged in</label>
          </div>
          <button class="form-button">submit</button>
        </div>
        <a href="#" class="form-forgot-password" aria-label="get reset password">Forgot Password?</a>
      </form>
    </div>
  </container>
</template>


<script>
export default {
  name: "Footer",
  props: {}
};
</script>

<style scoped>
</style>

// angularjs/src/app/container/container.component.ts
import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-container",
  templateUrl: "./container.component.html",
  styleUrls: ["./container.component.css"]
})
export class ContainerComponent implements OnInit {
  constructor() {}

  ngOnInit() {}
}

<div class="main-container">
  <img
    src="https://admin.skavacommerce.com/admin/studio/customlib/img/loginBanner.jpg"
    alt=" Business related photo"
    class="business-picture"
  />
  <div class="form-wrapper">
    <h1 class="form-title">Sign In</h1>
    <form class="form-signin">
      <div icontype="mail" class="form-fields">
        <label class="form-label" for="maillabel">Your Email</label>
        <input type="text" id="maillabel" name="maillabel" />
      </div>
      <div icontype="lock" class="form-fields">
        <label class="form-label" for="passowrdlabel">Your Password</label>
        <input type="password" id="passowrdlabel" name="passowrdlabel" />
      </div>
      <div class="button-group">
        <div class="loggedin-wrapper">
          <div class="form-checkbox">
            <input checked type="checkbox" id="loggedin-checked" />
            <label class="checkbox-support" for="loggedin-checked"></label>
          </div>
          <label class="loggedin-label" for="loggedin-checked"
            >Keep me logged in</label
          >
        </div>
        <button class="form-button">submit</button>
      </div>
      <a href="#" class="form-forgot-password" aria-label="get reset password"
        >Forgot Password?</a
      >
    </form>
  </div>
</div>
